SELECT * from customer;

-- Q1) what is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender;

-- Q2) which customers used a discount but still spend more than the average purchase amount?
select customer_id, purchase_amount from customer 
where purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3) top 5 products with hightse avg review rating?
select item_purchased, purchase_amount, review_rating from customer
where review_rating > (select avg(review_rating) from customer) limit 5;

-- Q4) compare the avg purchase amounts between standard and express shipping?
select shipping_type, avg(purchase_amount) as average_purchase_amount from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5) do subscribe costumers spend more? compare avg spend and total revenue between
-- subscribers and non subscribers?
select count(customer_id) as total_customers ,subscription_status, avg(purchase_amount), sum(purchase_amount) as total_revenue 
from customer
group by subscription_status;

-- Q6) which 5 products have the highest percentage of purchases with discounts applied?
-- select item_purchased, sum(purchase_amount) as total_purchases from customer
-- where discount_applied = 'Yes'
-- group by item_purchased
-- order by total_purchases desc
-- limit 5;

select item_purchased ,  sum(purchase_amount) as total_purchases,
sum(case when discount_applied='Yes' then 1 else 0 end ) * 100/ count(*) as percentage from customer 
group by 1
order by percentage desc
limit 5;

-- Q7) segment customers into new, returning and loyal based on their 
-- total number of previous purchases and show the count of each segment?
select customer_id, previous_purchases, case
when previous_purchases<2 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal'
end as customer_segment
from customer;

-- Q8) what is the top 3 most purchased products within each category?
-- select item_purchased, category
-- from customer
-- group by item_purchased, category
-- order by item_purchased desc
-- limit 3
with item_count as(
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders from item_count;

-- Q9) are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) from customer
where previous_purchases > 5 
group by subscription_status;

-- Q10) what is the revenue contribution of each age group
select age_group, sum(purchase_amount) as total_revenue 
from customer
group by age_group
order by total_revenue desc;
